### ISSUE TITLE
README

### ISSUE THREAD

**Issue by yosrigam** [Subhasish-Negel/CryptoDiction-TheNextVersion_of_CryptoPredict#2]
Hey, 
How is the project going? The last commit was last year and the is no description how to use it.
Could you add a better readme on how to install and use this project and how to feed the model fresh data to analyse?  
Thank you in advance.

**Comment by Subhasish-Negel** [comment]
Hey Yosri, Thanks for connecting. I hope you find these answers useful.


Q. "How is the project going? The last commit was last year."
A: This was my final year college project, which I completed on my own. Now that I have graduated, I am not working on it anymore. This is mostly because I shifted to web development as my career choice. It's very hard to get a job in the Data Science sector as a fresher, at least in India.

Q: "There is no description of how to use it."
A: This is a Streamlit-based app. Streamlit provides free hosting for apps created using Streamlit, and this project is also hosted on their server. However, they put apps to sleep if there are no visitors for some days, and it will take some seconds to wake the app up. You can access the app by clicking on the link provided in the 'about' section or [here](https://cryptodiction.streamlit.app/). If you want to run it locally on your PC, simply run the main Python file using the Streamlit run command. Learn more [here](https://docs.streamlit.io/knowledge-base/using-streamlit/how-do-i-run-my-streamlit-script).

Q: "Could you add a better readme on how to install and use this project?"
A: I am not really feeling up to it right now, sorry. Maybe in the future. But as I instructed, it's very easy to run the file :) Also, don't forget to install all the necessary packages mentioned in the requirements.txt. All the packages have their versions mentioned as required for the app to run without any problems. You can try to install the latest version of any of those packages to experiment, but the app might not work.

Q: "How to feed the model fresh data to analyze?"
A: So, I actually forgot to attach the script last year, which I used to create the LSTM model. Now, I have updated the repo with the notebook file. Although today I have tried to create a new model using latest data, for some reason, the model is not working with my app. So, I reverted back to the old model. You can try and experiment with the notebook to create a different model based on what you think will be best for you.

I hope this helps. If you have any more questions, let me know.
